server:
  context-path: /ems2
  port: 8989
  jsp-servlet:
    init-parameters:
      development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: edu.shanda.entity
  mapper-locations: mapper/*DAOMapper.xml
